server:
  context-path: /qtyd-zuul/
  port: ${server.port}
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://${security.user.name}:${security.user.password}@${eureka.host}:${eureka.port}/eureka-server/eureka/
spring:
  profiles:
    active: test
  application:
      name: qtyd-zuul
zuul: #网关配置
  routes:
    api-a: #网关服务1
      path: /api-test/**
      url: http://localhost:8765/
    api-b: #网关服务2
      path: /api-activity/** #网关转发请求地址
      serviceId: activity-provider-service #对应暴露的提供者服务名
  ratelimit:
    enabled: true
    behind-proxy: true
    policy-list:
      api-a:
        - limit: 3
          refresh-interval: 60
          type:
            - user
            - origin
            - url

