server:
  context-path: /eureka-server/ #项目上下文
  port: ${server.port} #服务端口
spring:
  profiles:
    active: test #指定启动读取的配置文件
  application:
    name: eureka-server #服务名
eureka: #注册中心配置
  server:
    enableSelfPreservation: false
    eviction-interval-timer-in-ms: 4000
  instance:
    hostname: ${eureka.host}
    ip-address: ${eureka.ip.address}
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${security.user.name}:${security.user.password}@${eureka.host}:${server.port}/eureka-server/eureka/
security: #认证
  basic:
    enabled: ${security.basic.enabled} #开启认证
  user:
    name: ${security.user.name}
    password: ${security.user.password}


