server:
#  context-path: /activity-provider-service/ #由于使用了zuul网关，需要关闭上下文
  port: ${server.port} #提供者服务端口
eureka: #提供者服务配置
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://${security.user.name}:${security.user.password}@${eureka.host}:${eureka.port}/eureka-server/eureka/
spring: #指定启动配置文件
  profiles:
    active: test
  application:
      name: activity-provider-service
  redis:
      database: 0
      host: ${redis.host}
      pool.max-active: 8
      pool.max-idle: 8
      pool.min-idle: 0
      pool.max-wait: -1
      port: 6379
      timeout: 0
      password: ${redis.password}
management: #关闭security认证，让消费者可以访问进来
  security:
    enabled: false
feign:
  httpclient:
    enabled: true
#####################################################################################################
# mysql 属性配置
datasource:
  driver-class-name: com.mysql.jdbc.Driver
  url: jdbc:mysql://192.168.116.128:3306/qttz_cashier_xiamen
  username: root
  password: 258369
#  jpa:
#    hibernate:
#      #ddl-auto: create #ddl-auto:设为create表示每次都重新建表
#      ddl-auto: update #ddl-auto:设为update表示每次都不会重新建表
#    show-sql: true
#####################################################################################################
#logging:
#  config: classpath:logback-spring.xml

